import os
from openai import OpenAI
from pydantic import BaseModel, Field
from typing import List
from dotenv import load_dotenv

# Initialize environment variables from .env file
load_dotenv()
client = OpenAI(api_key=os.environ.get('OPENAI_API_KEY'))


class Route(BaseModel):
    """Data model for a single flight route suggestion."""
    origin: str = Field(description="3-letter IATA code of the departure airport")
    dest: str = Field(description="3-letter IATA code of the arrival airport")
    avg_price: int = Field(description="Estimated market price in PLN for the chosen trip type")
    threshold: int = Field(description="Price in PLN below which the flight is considered a 'gem' deal")


class RouteList(BaseModel):
    """Container for a list of suggested routes generated by the AI."""
    routes: List[Route] = Field(description="List of 3 to 5 optimal travel routes")


def generate_routes_for_query(user_query: str, trip_type_desc: str) -> List[dict]:
    """
    Uses GPT-4o to translate natural language into structured airport codes
    and estimate baseline market prices.
    """
    prompt = f"""
    User is looking for flights: "{user_query}".
    Trip type: {trip_type_desc}.

    Task: Generate up to 5 sensible IATA airport combinations.
    For each route, estimate a baseline market price in PLN and a "gem threshold"
    based on your internal knowledge of global flight pricing for a {trip_type_desc} trip.
    """

    # Using OpenAI Structured Outputs (parsing into RouteList model)
    completion = client.beta.chat.completions.parse(
        model="gpt-4o-2024-08-06",
        messages=[
            {"role": "system",
             "content": "You are an expert travel planner fluent in IATA codes and global flight pricing."},
            {"role": "user", "content": prompt}
        ],
        response_format=RouteList,
    )

    # Return as list of dictionaries for easier processing in main.py
    return [route.model_dump() for route in completion.choices[0].message.parsed.routes]